- name: Deploy to EC2
  hosts: localhost
  connection: local

  tasks:
    - name: Launch EC2 instance
      ec2:
        instance_type: t2.micro
        image: ami-013f17f36f8b1fefb
        region: us-east-1
        key_name: devops
        vpc_subnet_id: subnet-99d0b9ff
        assign_public_ip: yes
        wait: yes
        count: 1
        group: eshop
        aws_access_key: "ASIAQFYTMD4WLQGQJIGM"
        aws_secret_key: "SXQovr0OVO9DSa/GrbvRL9+ss4DUniErb9mgo3C9"
        aws_security_token: "IQoJb3JpZ2luX2VjEOb//////////wEaCXVzLXdlc3QtMiJGMEQCIFOqghMiapz1V7mbUTuMVDXRuq01xYPjHyvWoCUr63gnAiAgw3oEkSrTRmb6p4MQlwb23DUE3dzzM2mTcZc86FBL3iqvAghfEAAaDDAxMjM4ODY3MTI3NiIMfeKddGVSET38mUC8KowCL/m7Jv7ve+1j2IkOn0Od+AYblmOAnlWywkwMVM2KHnAGkJOMZt5/kqD4zUSvdwuOMH8u1bRLW4yQ1KQrK8JT4Bz1LrArYHcpP6aamUbI90nGSK890ssILZrgLX+b3VxPvo5WUn68jAvtpfX+cryp9kyqyJo3nUywsLOVd6z0euq7qbNxx3cD2vq5OUTaS+ETJnfxMbYCG0sviVC244WyASyQORSTbJb3t3xw0CrMRfH4LRvgRAf9UauDukBPprOeRb1aYJtYd6Ls15Vi1oafZFDwku6/aSTYGkCidjMLxifryPtKG03bmRZoEaL3BS5STqRGDMKA+oe17tqRx/9938AiYzG2UeO4Sgsj/TCD0qWEBjqeATumwh1lg4hHpV8zLoW9q/5sR5mQmTiyyui5w2X8PKcwSVOTfpTwDUL2+e+HdlnaoDHf21Xq9dF7Xqsp0LChfPcO/g69R9++59+gHc4gW0WETTeIKtYDdV9mrVTK+pspc/0lhzYmfQOtva0ncsOLk6rZGhERY6znZlDC24YP3zm3wanhOgMnzXLdPXe3ajqt5hJkvtjXxkiLIXL4L5p2"
      register: ec2

    - name: Add instance host to group
      add_host: hostname={{ item.public_dns_name }} groupname=launched
      with_items: "{{ec2.instances}}"

    - name: Wait for SSH connection
      wait_for: host={{ item.public_dns_name }} port=22 delay=30 timeout=300 state=started
      with_items: "{{ec2.instances}}"

- name: Configure EC2
  hosts: launched
  connection: ssh

  tasks:
    - name: Install docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
      become: yes
    - service:
        name: docker
        state: started
        enabled: yes
      become: yes
    - name: Get project files from git
      git:
        repo: "https://github.com/milenig/4IT572_circleci.git"
        dest: ./app
    - name: Build docker with eshop
      shell: cd app && docker build -t myeshop:latest .
      become: yes
    - name: Run Docker with eshop
      shell: docker run -p 80:3000 myeshop
      async: 45
      poll: 10
      become: yes
    - wait_for:
        port: 80
